# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    default_filter_set_settings:
        format: webp

    resolvers:
        default:
            web_path: ~

#    webp:
#        generate:    true
#        quality:     100
#        cache:       ~
#        data_loader: ~
#        post_processors: []

    filter_sets:
        cache: ~

        # the name of the "filter set"
        my_thumb:

            # adjust the image quality to 75%
            quality: 90

            # list of transformations to apply (the "filters")
            filters:

                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [450, 300], mode: outbound }


        # name our first filter set "my_heighten_filter"
        heighten_filter:
            filters:
                # use and setup the "relative_resize" filter
                relative_resize:
                # given 50x40px, output 75x60px using "heighten" option
                    heighten: 400
                    allow_upscale: true
                    quality: 80

        big:
            filters:
                relative_resize:
                    heighten: 800
                    allow_upscale: true