name: app

type: php:7.4

runtime:
    extensions:
        - pdo_pgsql
        - apcu
        - mbstring
        - sodium
        - iconv
        - ctype
        

variables:
    php:
        # uncomment on PHP 7.4+
        opcache.preload: /app/config/preload.php

build:
    flavor: none

disk: 512

relationships:
    database: "db:postgresql"

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"



mounts:
    "/var": { source: local, source_path: var }
    #'/public/uploads': { source: service, service: files, source_path: uploads }
    '/public/uploads': { source: local, source_path: uploads }

hooks:
    build: |
        set -x -e

        curl -s https://get.symfony.com/cloud/configurator | (>&2 bash)
        
        (>&2 symfony-build)

    deploy: |
        set -x -e

        (>&2 symfony-deploy)

timezone: Europe/Paris

crons:
    snapshot:
        spec: 0 5 * * *
        cmd: |
            # only run for the master branch, aka production
            if [ "$SYMFONY_BRANCH" = "master" ]; then
                croncape symfony ... --no-wait
            fi